import React, { createContext, useState, useEffect, useContext } from 'react';

const translations = {
  en: {
    'nav.live_data': 'Live Data',
    'nav.summary': 'Summary',
    'nav.data_capture': 'Data Capture Rate',
    'nav.back_to_map': 'Back To Map',
    'profile.settings': 'Profile Settings',
    'profile.help': 'Help Center',
    'profile.logout': 'Logout',
    'live.title': 'Live Data',
    'live.view_type': 'View Type',
    'live.tabular_view': 'Tabular View',
    'live.map_view': 'Map View',
    'live.grid_view': 'Grid View',
    'live.stations': 'Stations',
    'live.city_centre': 'City Centre',
    'live.mobile_station': 'Mobile Station',
    'live.qidfa': 'Qidfa',
    'live.lafarge_cems': 'Lafarge Cems',
    'live.date': 'Date',
    'live.today': 'Today',
    'live.daily': 'Daily',
    'live.monthly': 'Monthly',
    'live.yearly': 'Yearly',
    'live.aqi_index': 'AQI Index',
    'live.moderate': 'Moderate',
    'live.live_aqi': 'Live AQI',
    'live.pollutant_metrics': 'Pollutant Metrics',
    'live.wind_speed': 'Wind Speed',
    'live.wind_direction': 'Wind Direction',
    'live.light_breeze': 'Light breeze',
    'live.temperature': 'Temperature',
    'live.ideal_temp': 'Ideal Temperature',
    'live.atmospheric_pressure': 'Atmospheric Pressure',
    'live.balanced_pressure': 'Balanced Air Pressure',
    'live.solar_radiation': 'Solar Radiation',
    'live.high_solar': 'High Solar Intensity',
    'live.relative_humidity': 'Relative Humidity',
    'live.humidity_normal': 'Humidity is normal',
    'live.fujairah': 'Fujairah',
    'analytics.parameters': 'Parameters',
    'analytics.report_type': 'Report Type',
    'analytics.daily_summary': 'Daily Summary',
    'analytics.hourly_summary': 'Hourly Summary',
    'analytics.min': 'Min',
    'analytics.max': 'Max',
    'analytics.avg': 'Avg',
    'analytics.download': 'Download',
    'datacapture.title': 'Data Capture Rate',
    'datacapture.tab1': 'Data Capture Rate',
    'datacapture.tab2': 'Valid Data Capture',
    'datacapture.collected_records': 'No.Of Collected Records',
    'datacapture.valid_records': 'No.Of Valid Records',
    'datacapture.sno': 'S.No',
    'datacapture.station_name': 'Station Name',
    'datacapture.parameter': 'Parameter',
    'datacapture.expected_records': 'No.Of Expected Records',
    'datacapture.percent_avail': 'Percent Availability',
    'login.title': 'Login',
    'login.subtitle': 'Please enter your details.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.remember_me': 'Remember me',
    'login.forgot_password': 'Forgot password?',
    'login.no_account': "Don't have an account?",
    'login.sign_up': 'Sign up',
    'dropdown.none': 'None',
    'landing.nav.our_air_quality': 'Our Air Quality',
    'landing.nav.live_air_quality': 'Live Air Quality',
    'landing.nav.contact_us': 'Contact Us',
    'landing.hero.title': 'Real-Time Air Quality Monitoring',
    'landing.hero.subtitle': 'for Fujairah Emirate',
    'landing.hero.view_live': 'View Live AQI',
    'landing.stats.current_aqi': 'Current AQI',
    'landing.stats.good': 'Good',
    'landing.stats.active_stations': 'Active Stations',
    'landing.stats.monitoring': 'Monitoring',
    'landing.stats.coverage_area': 'Coverage Area',
    'landing.stats.fujairah': 'Fujairah',
    'landing.map.title': 'Live Air Quality Map',
    'landing.map.desc': 'Explore real-time air quality metrics across the Fujairah Emirate.',
    'landing.map.city_centre': 'City Centre',
    'landing.map.aqi_index': 'Air Quality Index',
    'landing.map.primary': 'Primary',
    'landing.map.secondary': 'Secondary',
    'landing.map.weather': 'Weather',
    'landing.map.last_updated': 'Last Updated',
    'landing.dash.safety_level': 'Air Quality Safety Level',
    'landing.dash.pollutant': 'Main Contributing Pollutant',
    'landing.dash.suburban': 'Suburban Traffic',
    'landing.dash.natural': 'Natural Sources',
    'landing.dash.causes': 'Possible Causes / Activities',
    'landing.dash.measures': 'Protective Measures',
    'landing.dash.trend': 'Hourly AQI Trend',
    'landing.dash.moderate': 'Moderate',
    'landing.dash.unhealthy_sg': 'Unhealthy for Sensitive Groups',
    'landing.dash.unhealthy': 'Unhealthy',
    'landing.dash.very_unhealthy': 'Very Unhealthy',
    'landing.dash.pm10': 'PM10 (Particulate Matter)',
    'landing.dash.respirable': 'Respirable dust',
    'landing.dash.measures.windows': 'Keep Windows Closed',
    'landing.dash.measures.outdoor': 'Reduce Outdoor Activity',
    'landing.dash.measures.mask': 'Wear N95 Mask',
    'landing.dash.measures.purifier': 'Use Air Purifier',
    'landing.footer.copyright': '© 2026 AQMS Fujairah. All rights reserved.',
    'landing.footer.terms': 'Terms of Service',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.support': 'Support'
  },
  ar: {
    'nav.live_data': 'البيانات المباشرة',
    'nav.summary': 'الملخص',
    'nav.data_capture': 'معدل التقاط البيانات',
    'nav.back_to_map': 'العودة إلى الخريطة',
    'profile.settings': 'إعدادات الملف الشخصي',
    'profile.help': 'مركز المساعدة',
    'profile.logout': 'تسجيل الخروج',
    'live.title': 'البيانات المباشرة',
    'live.view_type': 'نوع العرض',
    'live.tabular_view': 'عرض جدولي',
    'live.map_view': 'عرض الخريطة',
    'live.grid_view': 'عرض شبكي',
    'live.stations': 'المحطات',
    'live.city_centre': 'مركز المدينة',
    'live.mobile_station': 'المحطة المتنقلة',
    'live.qidfa': 'قدفع',
    'live.lafarge_cems': 'لافارج سيمز',
    'live.date': 'التاريخ',
    'live.today': 'اليوم',
    'live.daily': 'يوميا',
    'live.monthly': 'شهريا',
    'live.yearly': 'سنويا',
    'live.aqi_index': 'مؤشر جودة الهواء',
    'live.moderate': 'معتدل',
    'live.live_aqi': 'مؤشر جودة الهواء المباشر',
    'live.pollutant_metrics': 'مقاييس الملوثات',
    'live.wind_speed': 'سرعة الرياح',
    'live.wind_direction': 'اتجاه الرياح',
    'live.light_breeze': 'نسيم عليل',
    'live.temperature': 'درجة الحرارة',
    'live.ideal_temp': 'درجة حرارة مثالية',
    'live.atmospheric_pressure': 'الضغط الجوي',
    'live.balanced_pressure': 'ضغط هواء متوازن',
    'live.solar_radiation': 'الإشعاع الشمسي',
    'live.high_solar': 'كثافة شمسية عالية',
    'live.relative_humidity': 'الرطوبة النسبية',
    'live.humidity_normal': 'الرطوبة طبيعية',
    'live.fujairah': 'الفجيرة',
    'analytics.parameters': 'المعلمات',
    'analytics.report_type': 'نوع التقرير',
    'analytics.daily_summary': 'الملخص اليومي',
    'analytics.hourly_summary': 'الملخص كل ساعة',
    'analytics.min': 'الأدنى',
    'analytics.max': 'الأقصى',
    'analytics.avg': 'المتوسط',
    'analytics.download': 'تنزيل',
    'datacapture.title': 'معدل التقاط البيانات',
    'datacapture.tab1': 'معدل التقاط البيانات',
    'datacapture.tab2': 'التقاط البيانات الصالحة',
    'datacapture.collected_records': 'عدد السجلات المجمعة',
    'datacapture.valid_records': 'عدد السجلات الصالحة',
    'datacapture.sno': 'م.',
    'datacapture.station_name': 'اسم المحطة',
    'datacapture.parameter': 'المعلمة',
    'datacapture.expected_records': 'عدد السجلات المتوقعة',
    'datacapture.percent_avail': 'نسبة التوفر',
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'الرجاء إدخال بياناتك.',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.remember_me': 'تذكرني',
    'login.forgot_password': 'هل نسيت كلمة المرور؟',
    'login.no_account': 'ليس لديك حساب؟',
    'login.sign_up': 'التسجيل',
    'dropdown.none': 'لا شيء',
    'landing.nav.our_air_quality': 'جودة الهواء لدينا',
    'landing.nav.live_air_quality': 'جودة الهواء المباشرة',
    'landing.nav.contact_us': 'اتصل بنا',
    'landing.hero.title': 'مراقبة جودة الهواء في الوقت الفعلي',
    'landing.hero.subtitle': 'لإمارة الفجيرة',
    'landing.hero.view_live': 'عرض المؤشر المباشر',
    'landing.stats.current_aqi': 'المؤشر الحالي',
    'landing.stats.good': 'جيد',
    'landing.stats.active_stations': 'المحطات النشطة',
    'landing.stats.monitoring': 'مراقبة',
    'landing.stats.coverage_area': 'منطقة التغطية',
    'landing.stats.fujairah': 'الفجيرة',
    'landing.map.title': 'خريطة جودة الهواء المباشرة',
    'landing.map.desc': 'استكشف مقاييس جودة الهواء في الوقت الفعلي في إمارة الفجيرة.',
    'landing.map.city_centre': 'مركز المدينة',
    'landing.map.aqi_index': 'مؤشر جودة الهواء',
    'landing.map.primary': 'أساسي',
    'landing.map.secondary': 'ثانوي',
    'landing.map.weather': 'الطقس',
    'landing.map.last_updated': 'آخر تحديث',
    'landing.dash.safety_level': 'مستوى سلامة جودة الهواء',
    'landing.dash.pollutant': 'الملوث الرئيسي المساهم',
    'landing.dash.suburban': 'حركة المرور في الضواحي',
    'landing.dash.natural': 'المصادر الطبيعية',
    'landing.dash.causes': 'الأسباب / الأنشطة المحتملة',
    'landing.dash.measures': 'التدابير الوقائية',
    'landing.dash.trend': 'اتجاه المؤشر كل ساعة',
    'landing.dash.moderate': 'معتدل',
    'landing.dash.unhealthy_sg': 'غير صحي للمجموعات الحساسة',
    'landing.dash.unhealthy': 'غير صحي',
    'landing.dash.very_unhealthy': 'غير صحي للغاية',
    'landing.dash.hazardous': 'خطير',
    'landing.dash.pm10': 'الجسيمات الدقيقة PM10',
    'landing.dash.respirable': 'الغبار القابل للتنفس',
    'landing.dash.measures.windows': 'أغلق النوافذ',
    'landing.dash.measures.outdoor': 'تقليل الأنشطة الخارجية',
    'landing.dash.measures.mask': 'ارتداء كمامة N95',
    'landing.dash.measures.purifier': 'استخدم منقي الهواء',
    'landing.footer.copyright': '© 2026 AQMS الفجيرة. جميع الحقوق محفوظة.',
    'landing.footer.terms': 'شروط الخدمة',
    'landing.footer.privacy': 'سياسة الخصوصية',
    'landing.footer.support': 'الدعم'
  }
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'ar' : 'en'));
  };

  const t = (key, fallback) => {
    return translations[lang][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
